version: '3.6'
services:
  db:
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=pvFQMzdN2Ky
      - POSTGRES_DB=todoAppDb
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
  backend:
    build: .
    command: python run.py
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DATABASE_URL=postgresql://dev:pvFQMzdN2Ky@db:5432/todoAppDb
      - SECRET_KEY=pvFQMzdN*2KypvFQMzdN*2KypvFQMzdN*2Ky
      - DEBUG=True
volumes:
  db_data:
