version: '3.6'
services:
  db:
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=todoApp
      - POSTGRES_PASSWORD=pvFQMzdN*2Ky
      - POSTGRES_DB=todoAppDB
      - POSTGRES_HOST_AUTH_METHOD=md5
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
  backend:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DATABASE_URL=postgresql://todoApp:pvFQMzdN*2Ky@db:5432/todoAppDB
      - SECRET_KEY=pvFQMzdN*2KypvFQMzdN*2KypvFQMzdN*2Ky
volumes:
  db_data:
